name: Build Android Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.7
          cache: true

      - name: Get Dependencies
        run: |
          flutter pub get
          dart pub global activate flutter_distributor

      - name: Build Project
        run: |
          NDK_PATH=$(ls -d $ANDROID_SDK_ROOT/ndk/* | tail -1)
          echo "ANDROID_NDK=$NDK_PATH" >> $GITHUB_ENV
          export ANDROID_NDK=$NDK_PATH
          dart setup.dart android --arch arm64 --env stable --out app

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FlClash-Release-arm64-v8a
          path: ./dist/**/*.apk
